version: '3'
services:
  test:
    environment:
      - NODE_ENV=test
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: yarn test
    ports:
    - "3001:3001"
    depends_on:
    - mongo_test
  mongo_test:
    image: mongo
    command: mongod --port 27016
