version: '3'
services:
  test:
    environment:
      - NODE_ENV=test
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: yarn test
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"