version: '3'
services:
  web:
    image: antoinert/tonto:action-latest
    ports:
    - "3000:3000"
    depends_on:
        postgres_test:
          condition: service_healthy
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: "tonto_prod"
      POSTGRES_USER: "tonto"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: "pg_isready -U tonto -d tonto_prod"
      interval: 5s
