version: '3'
services:
  web:
    image: antoinert/tonto:action-latest
    ports:
    - "3000:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo-backup:/data/db

volumes:
  mongo-backup:
